#Base İmage Çekmemiz Gerekiyor , python:alpine3.17 tag docker hub
#Python Docker Base image
FROM python:alpine3.17

WORKDIR /app

COPY . /app/

ENV Python_Dockerize=hello

CMD ["python3" , "main.py"]

